### ISSUE TITLE
Moving mail creates EES-TEMP folder sometimes

### ISSUE THREAD

**Issue by hopalongrock** [robert7k/moveMailShortcuts#12]
Hello!

I use  move mail shortcuts version 5 in TB 115.3.2

I move the message with Alt 6 (to avoid Alt 1 .. Alt 5 conflict) to Local Folders/Trash,, and rarely moving mail creates a EES-TEMP folder with the moved message in it .

With previous versions i didn't have this problem.
...
I see the new shortcuts working with Shift Alt, but folder 1 and 6 remained Alt 1 and Alt 6, probably because I originally used Alt 1, and later cI see the new shortcuts with Shift Alt, but folder 1 and 6 remained Alt 1 and Alt 6, probably because I originally used Alt 1, and later changed to Alt 6 to avoid the arisen conflict in ver 102, if I remember well.
hanged to Alt 6 to avoid the arisen conflict in ver 102, if I remember well.

May I modify them to Shift Alt 1 and Shift Alt 6 ?

**Comment by robert7k** [comment]
Are there any messages in the error console?

> May I modify them to Shift Alt 1 and Shift Alt 6 ?

Yes, that's also the new default values since the old shortcuts are now used by Thunderbird itself.

The EES-TEMP folder seems to originate from the [Edit Email Subject ](https://addons.thunderbird.net/en-US/thunderbird/addon/edit-email-subject/)extension. Do you have that installed? Is the error reproducible if you uninstall the extension?

**Comment by hopalongrock** [comment]
You are true, I have Edit Email Subject addon, and I use it very rarely. I disabled it, and watch what happens.

Thanks for your tip.

**Comment by hopalongrock** [comment]
Issue solved, I was careless, I did not notice the addon option to save the message before the renaming into the local folder "EES-Temp".

I'm sorry about it.
